using Certification_70_483.Shared;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using static Certification_70_483.Chapter_01.Objective_01_03.Flow72;

namespace Certification_70_483.Chapter_01.Objective_01_03
{
    //The compiler-generated code for a foreach loop
    class Flow73 : Starting
    {
        public Flow73(params string[] args) : base(args)
        {
        }
        public override void Start(params string[] args)
        {
           var people = new List<Person>
           {
               new Person() { FirstName = "John", LastName = "Doe"},
               new Person() { FirstName = "Jane", LastName = "Doe"},
           };

            /* Foreach code generated by compiler. */
            List<Person>.Enumerator e = people.GetEnumerator();

            try
            {
                Person v;
                while(e.MoveNext())
                {
                    v = e.Current;
                }
            }
            finally
            {
                System.IDisposable d = e as System.IDisposable;
                if (d != null) d.Dispose();
            }
            /***************************************/
        }


    }
}
